### ISSUE TITLE
Clipboard popup prevents shelf from auto-hiding

### ISSUE THREAD

**Issue by wltjr** [rbtylee/e21-modules-extra#1]
Minor issue that likely does not effect anyone who does not have the shelf set to auto-hide. It seems when you click on the clipboard icon, to get the popup of recent clipboard entries and/or go to settings or clear. That seems to stop the shelf from auto-hiding. It remains that way till I log out and in again, OR I go to the shelf's settings, uncheck auto-hide, hit apply, then re-check, and apply again. That gets it to hide again. Till next time I click on the icon.

Not sure offhand what is causing this. I assume issues with the module vs shelf. The others do not seem to have the same issue. Maybe need to change how the popup is generated, or something along those lines. I have not looked at the code at all. Just noticed the behavior.

**Comment by rbtylee** [comment]
Ok, I can verify this as well as verify this issue is also found in the e17 version of the clipboard module Bodhi Linux uses. It an interesting issue and rather odd no Bodhi user reported it. I personally don't auto-hide shelves but you would think some do who use this module and they would have reported it. 

Regardless I am accepting this issue, other than that not much to say now.

**Comment by wltjr** [comment]
As mentioned on IRC, I think this stems from the object used for the popup. While I thought it would be a simple switch. It seems a bit more complex. Seems to be difference of [e_menu_new](https://github.com/rbtylee/e21-modules-extra/blob/master/Clipboard/src/e_mod_main.c#L273) vs [e_gadcon_popup_new](https://git.enlightenment.org/core/enlightenment.git/tree/src/modules/clock/e_mod_main.c#n318) (e clock module). Likely a bit of coding to switch, more than swapping out objects.

**Comment by rbtylee** [comment]
Seems like an excessive amount of work wltjr. I appreciate your ideas tho. Anyway looked at the code this morning determined to see the problem with using e_menu_new and saw what I thought was the problem. And a simple fix. Just need to unfocus the clipboard gadget after it is clicked. Reluctantly went to work tho so testing debugging and committing had to wait. Regardless commit 6df624e address this issue.

Let me know if this issue is resolved for you.

**Comment by wltjr** [comment]
For this issue yes, as what you did seems to have resolved the issue. Though long term may be best to move to code like the other modules. Either way seems to have resolve the issue. Thanks!

**Comment by rbtylee** [comment]
Causal check of Bodhi's extra (e17) modules reveals  **e_menu_new** is used in 18 of them. I am unsure of any advantage of using **e_gadcon_popup_new** in place of it. But for the record this **e_menu_new** was the way Štefan originally implemented this functionality before I  started helping on it. I thought it was an unusual way to do it myself before I looked over other modules also using it. Anyway this falls under the category _if it is not broke don't fix it_.

**Comment by wltjr** [comment]
Sure, think it just maybe a change if you want to get this into E. Which long term it should be a module shipped with E as part of its default modules. Its a pretty core feature IMHO.

**Comment by wltjr** [comment]
Sadly this has come up again. Not sure if something caused a regression. If click on clipboard icon to view history. The shelf stops auto hiding. This was resolved for sure before.

**Comment by rbtylee** [comment]
Clearly I am going to have to take a closer look. The commit that broke it just removed a line of code that caused a seg fault when the clipboard history was opened by a hot key. At least it was the line of code valgrind revealed as spitting out errors.

**Comment by wltjr** [comment]
I am not sure what caused it. I had not updated clipboard or efl. Unless it had been that way since I last updated the clipboard package and my systems and I just now noticed. I doubt it was that line of code removed, but maybe.

**Comment by wltjr** [comment]
Working on this myself, and I think I resolved it for good. None the less, nothing for you to worry about. Feel free to use my changes and/or cherry pick as needed. Thanks!
